// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5118/' | (string & {});
};

export type WeatherForecast = {
    date?: string;
    temperatureC?: number | string;
    temperatureF?: number | string;
    summary?: null | string;
};

export type GetWeatherForecastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/WeatherForecast';
};

export type GetWeatherForecastResponses = {
    /**
     * OK
     */
    200: Array<WeatherForecast>;
};

export type GetWeatherForecastResponse = GetWeatherForecastResponses[keyof GetWeatherForecastResponses];
